server:
  port: ${PORT:8765}

spring:
  application:
    name: gateway

zuul:
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 60000
  routes:
    productos:
      path: /productos/**
      url: https://tfm-pwfs-productos.herokuapp.com
    security:
      path: /security/**
      url: https://tfm-pwfs-security.herokuapp.com
    facturacion:
      path: /facturacion/**
      url: https://tfm-pwfs-facturacion.herokuapp.com
  ignored-services: '*'

management:
  endpoints:
    web:
      exposure:
        include: '*'


logging:
  level:
    ROOT: info
    org.springframework.web: DEBUG

